### ISSUE TITLE
AnonymousHyperlink ref target is reversed in transformed AST

### ISSUE THREAD

**Issue by frantic1048** [frantic1048/Est#2]
Sample
-------------

```rst

RabbitHouse__

`Fleur de Lapin`__

.. __: http://gochiusa.wikia.com/wiki/Rabbit_House
.. __: http://gochiusa.wikia.com/wiki/Fleur_de_Lapin
```

Expected
-------------

- "RabbitHouse" points to `http://gochiusa.wikia.com/wiki/Rabbit_House`
- "Fleur de Lapin" points to `http://gochiusa.wikia.com/wiki/Fleur_de_Lapin`

Actual
-------------

- "RabbitHouse" points to `http://gochiusa.wikia.com/wiki/Fleur_de_Lapin`
- "Fleur de Lapin" points to `http://gochiusa.wikia.com/wiki/Rabbit_House`

**Comment by SilverRainZ** [comment]
:joy: reborn?

**Comment by frantic1048** [comment]
@SilverRainZ 回头看了一下，发现要修的东西也不是很多，先把 pegjs 实现搞到基本实用吧

~~都快摸一年了（~~

**Comment by frantic1048** [comment]
Resolved by https://github.com/frantic1048/Est/commit/3fcfd8d4a2d2930750776e7ff35e6b4839da5572

（´＿｀）
